CREATE TABLE users (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL,
  PersonalNumber INT UNIQUE NOT NULL,
  Email VARCHAR(20) NOT NULL,
  Password VARCHAR(30) NOT NULL,
  StatusId INT DEFAULT(0)
);